# Configuration file for the Sphinx documentation builder.
#
# The whole site is one Sphinx build: the narrative documentation is written in
# MyST Markdown under docs/src/guide/, and the API reference is generated by
# autodoc from the package docstrings (docs/src/api.md).

import os
import sys

# So autodoc can import the package from the checkout without installing it.
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__),
                                                "..", "..")))

# -- Project information -----------------------------------------------------
project = "PALSParserPy"
copyright = "2026, PALSParserPy Contributors"
author = "PALSParserPy Contributors"

# -- General configuration ---------------------------------------------------
extensions = [
    "myst_parser",              # MyST Markdown
    "sphinx.ext.autodoc",       # API reference from the docstrings
    "sphinx.ext.napoleon",      # Google-style Args:/Returns: sections
    "sphinx.ext.viewcode",      # "[source]" links
    "sphinx.ext.githubpages",   # emit .nojekyll for GitHub Pages
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
]

numfig = True

intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}

# -- autodoc -----------------------------------------------------------------
# Importing palsparserpy does not load the C library -- that happens lazily on
# the first call -- so the docs build needs no C++ toolchain.
autodoc_member_order = "bysource"
autodoc_typehints = "description"
autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
}

# -- MyST configuration ------------------------------------------------------
myst_enable_extensions = [
    "dollarmath",
    "amsmath",
    "deflist",
    "colon_fence",
    "linkify",
]
myst_heading_anchors = 3

# -- HTML output (Furo) ------------------------------------------------------
html_theme = "furo"
html_theme_options = {
    "source_repository": "https://github.com/pals-project/PALSParserPy",
    "source_branch": "main",
    "source_directory": "docs/src/",
    "navigation_with_keys": True,
    "sidebar_hide_name": False,
}
html_title = "PALSParserPy"
templates_path = ["_templates"]
html_static_path = ["_static"]
html_css_files = ["custom.css"]

# Add the "GitHub ↗" link to the Furo sidebar on every page.
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "sidebar-external-links.html",
        "sidebar/scroll-end.html",
    ]
}
